CREATE TABLE IF NOT EXISTS table_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    reservation_id BIGINT NOT NULL UNIQUE,
    reservation_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_assignment_table FOREIGN KEY (table_id) REFERENCES tables(id),
    CONSTRAINT uq_assignment_table_slot UNIQUE (table_id, reservation_time)
);